spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practicum
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: none
    open-in-view: false
logging:
  level:
    root: INFO
  file:
    name: practicum.log
  logback:
    rollingpolicy:
      clean-history-on-start: true